name: Make a release
on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          tag_name: ${{steps.previous_tag.outputs.tag}}
      - name: Release
        uses: softprops/action-gh-release@v2
